name: NPM Publish Beta

on:
  push:
    tags: ['*.*.*-beta.*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -f
      - run: npm run test:coverage

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  send-slack-message:
      needs: publish-npm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - run: bash ./scripts/release-notes.sh
          env:
            RELEASE_SLACK_WEBHOOK_URL: ${{secrets.RELEASE_SLACK_WEBHOOK_URL}}